import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
      {/* <Image
        width={300}
        height={300}
        src="https://localhost:7063/images/3f42414f-bf60-47b4-aae3-1d94d69cb4df.jpg"
        alt="cs"
        unoptimized
      />      */}
       {children}
      </body>
    </html>
  );
}
